services:

  db:
    image: postgres:16
    container_name: securecase_pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: securecase_user
      POSTGRES_PASSWORD: securecase_pass
      POSTGRES_DB: securecase_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - securecase_net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U securecase_user -d securecase_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: securecase_api
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - securecase_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: securecase_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: system@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json
    networks:
      - securecase_net

networks:
  securecase_net:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
